#!/bin/bash
# Setup instructions for the length generalization study

echo "=============================================="
echo "LENGTH GENERALIZATION STUDY - SETUP GUIDE"
echo "=============================================="
echo ""
echo "To run the experiment, you need to:"
echo ""
echo "1. Activate your Python environment with PyTorch:"
echo "   source /path/to/your/env/bin/activate"
echo "   # OR"
echo "   conda activate your_env_name"
echo ""
echo "2. Verify PyTorch is available:"
echo "   python3 -c 'import torch; print(torch.__version__)'"
echo ""
echo "3. Launch the experiment:"
echo "   bash launch_length_gen_study_gpu7.sh"
echo ""
echo "=============================================="
echo "ALTERNATIVE: Direct execution"
echo "=============================================="
echo ""
echo "If you have PyTorch installed, you can run directly:"
echo "  CUDA_VISIBLE_DEVICES=7 python3 train_length_gen_study.py \\"
echo "    --output_dir length_gen_study_gpu7 \\"
echo "    --max_train_steps 100000 \\"
echo "    --num_eval_checkpoints 50"
echo ""
echo "=============================================="
echo "MONITORING"
echo "=============================================="
echo ""
echo "Once running, monitor progress with:"
echo "  python3 monitor_length_gen_study.py --exp-dir length_gen_study_gpu7 --watch"
echo ""
echo "Analyze results after completion:"
echo "  python3 analyze_length_gen_study.py --exp-dir length_gen_study_gpu7"
echo ""
echo "=============================================="
